apiVersion: v1
kind: ConfigMap
metadata:
        namespace: metallb-system
        name: config
data:
        config: |
                address-pools:
                        - name: intern
                          protocol: layer2
                          addresses:
                                  - 172.20.11.2-172.20.11.254
                        - name: dmz
                          protocol: layer2
                          addresses:
                                  - 172.21.11.2-172.20.11.254
                          auto-assign: false
                
